language: go

cache:
  directories:
    - $GOPATH/pkg/mod

env:
- GO111MODULE=on

go:
  - 1.13.x

script:
  - make ensure-deps
  - make test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
