# Cloudbuild pipeline for a build with an image
# that passes the vuln policy
steps:
  # Build a 'bad' image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker build -t gcr.io/$PROJECT_ID/binauthz-test:latest -f ./Dockerfile.bad .
    id: build
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/binauthz-test:latest &&
      docker image inspect gcr.io/$PROJECT_ID/binauthz-test:latest --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: push
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
     - -c
     - |
        itoken=$(curl -X POST -H "content-type: application/json" \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -d '{"audience": "${_SERVICE_URL}"}' \
        https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/${_SERVICE_ACCOUNT}:generateIdToken) && \
        curl -X POST \
        -H "Authorization: Bearer $(echo $itoken | awk -F'\"' '{print $4}')" \
        -H "Content-Type: application/json" \
        -d "{\"image_url\": \"$(cat image-digest.txt)\"}" \
        ${_SERVICE_URL}/all
    waitFor: push
    id: vulnsign
substitutions:
    _SERVICE_URL: MISSING_SERVICE_URL # Use `gcloud builds submit --substitutions ` to set this value
    _SERVICE_ACCOUNT: MISSING_SERVICE_ACCOUNT # Use `gcloud builds submit --substitutions ` to set this value
images: ['gcr.io/$PROJECT_ID/binauthz-test:latest']